{
  viewer {
    gists(privacy: SECRET, first: 100, orderBy: {field: CREATED_AT, direction: DESC} ) {
      totalCount
      pageInfo {
        endCursor
        hasNextPage
      }
      edges {
        repository: node {
          id
          name
          createdAt
          description
          files {
            encodedName
            encoding
            extension
            name
            size
          }
        }
      }
    }
  }
}
